# https://github.com/realm/SwiftLint?tab=readme-ov-file#configuration

# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - vertical_parameter_alignment
  - todo
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # find all the available rules by running: `swiftlint rules`
  - weak_delegate
  - self_binding
  - operator_usage_whitespace
  - private_outlet
  - private_action
  - private_subject
  - private_swiftui_state

analyzer_rules: # rules run by `swiftlint analyze`
  - explicit_self
  - unused_import

excluded:
  - Build Configurations
  - CxxCEF/BuildConfigurations.xcconfig
  - Build-Tools
  - Dependencies/Sparkle
  - Dependencies/CameraExtension/.build
  - Dependencies/Common/.build

# If true, SwiftLint will not fail if no lintable files are found.
allow_zero_lintable_files: false

# If true, SwiftLint will treat all warnings as errors.
strict: false

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 250
# they can set both implicitly with an array
type_body_length:
  - 400 # warning
  - 500 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded:
    - iPhone # excluded via string
    - T
    - API
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - url
    - key
    - os
    - ac
    - on
    - to
    - r
    - g
    - b
    - x
    - y
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)
nesting:
  type_level:
    warning: 2
trailing_comma:
  mandatory_comma: true
