# win-build-az-pipeline.yml
#
# This pipeline builds the Windows hybrid app and publishes the build artifacts.

# https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers
trigger: none

# https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers
# Important: Don't use path filters when requiring this pipeline to run as a GitHub PR check, see
# https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
pr:
  autoCancel: true
  branches:
    include:
      - main
  drafts: true

jobs:
  - template: templates/win-az-pipeline.yml
